/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        WordChooser chooser = new WordChooser();
        Game game = new Game(chooser);
        game.play();
    }
}
